### PR TITLE
Thanks again for your PR.  I re-read your changes and tested it locally.

### PR DESCRIPTION
**Pull request by hannesm**
I tweaked the code a bit to use stricter types and conform more cleanly with
the RFC.

In RFC 7301, it says 'The protocol identified in the
"application_layer_protocol_negotiation" extension type in the ServerHello
SHALL be definitive for the connection, until renegotiated.'.

This means, the alpn_protocol is local to each renegotiation (instead of global
for a complete TLS session):
- move alpn_protocol from handshake_state (which is TLS-session global, such
  as protocol version that may not change during a renegotiation) to
  session_data (where all the other parameters of a negotiation are kept)

From RFC 7301 'except that the "ProtocolNameList" MUST contain exactly one
"ProtocolName".'  To ensure this invariant, Core.server_extension now contains
`` `ALPN of string `` -- and the Reader and Writer are adjusted to deal with it.
This is similar to how `` `Hostname `` works: the client_extension carries a single
string, while the server_extension must be empty (`` `Hostname `` is a constructor
of cardinality 0).  The Reader and Writer are adapted for this change.

In epoch_data, I renamed peer_alpn to alpn_protocol.  The prefix `peer_` is used
for information about the other endpoint, but alpn is (similar to ciphersuite)
negotiated once.

Handshake_client safety: if server responded with a alpn protocol, ensure it is
one we actually asked for.

Both Handshake_client and Handshake_server now include the negotiated
alpn_protocol in the session_data.

Handshake_server processes the ALPN extension in answer_client_hello_common,
which is used for every renegotiation.  Previously, the ALPN was only processed

Removed `type alpn_protocol = string`, no reason to alias the type.
in the initial handshake.  Also, `first_match` (from Utils) is reused.

### CODE REVIEW

**Comment by hannesm** [comment]
sorry for (a) the delayed work on that and (b) the more extensive review + PR from me.  please let me know if you agree with my changes on top of your branch, and especially if they work for you fine.

**Comment by bobbypriam** [comment]
@hannesm, Thank you so much for looking into this.

> move alpn_protocol from handshake_state (which is TLS-session global, such
as protocol version that may not change during a renegotiation) to
session_data (where all the other parameters of a negotiation are kept)

Ah, yes, this make sense. I particularly was confused about the term "session" there, since there's also `session_data` which turned out not to be about global TLS-session.

> To ensure this invariant, Core.server_extension now contains `ALPN of string

Looking back, I should have gone with this too to make sure the type is stricter. I'm onboard with this change.

Overall, I think this change makes it better, so code-wise I'm okay with merging it to my branch. I'm going to test it locally first to do some trivial checks, I'll let you know in a moment.

**Comment by bobbypriam** [comment]
@hannesm Yep, it's working and perfectly compatible with `openssl`, both the protocol selection and failure on no match. I think after this we are only missing an example of how a client can extract the selected protocol from `epoch_data`, e.g. when using Lwt.

I can merge it to this branch if you want, but I think you should be able to merge it yourself (I enabled the "allow edits from maintainers" option on the original PR). Feel free to do as you see fit!

**Comment by bobbypriam** [comment]
I will merge this so we can continue the review on the original PR.

**Pull request merged**
